#The try block lets you test a block of code for errors.
#The except block lets you handle the error.
#print(varNum1)
try:
    print(varNum1)
    
except:
    print("Something went wrong.")
    

